# Generated by Django 5.2.4 on 2025-08-17 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocks',
                'indexes': [models.Index(fields=['user'], name='idx_blocks_user'), models.Index(fields=['blocked_user'], name='idx_blocks_blocked')],
                'constraints': [models.UniqueConstraint(fields=('user', 'blocked_user'), name='uq_blocks_pair'), models.CheckConstraint(condition=models.Q(('user', models.F('blocked_user')), _negated=True), name='ck_blocks_not_self')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follows',
                'indexes': [models.Index(fields=['follower'], name='idx_follows_follower'), models.Index(fields=['following'], name='idx_follows_following')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='uq_follows_pair'), models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='ck_follows_not_self')],
            },
        ),
    ]
