# Generated by Django 5.2.4 on 2025-09-03 01:37

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_bookmark_postlike_repost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hashtags',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_hashtag_name_lower')],
            },
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_hashtags', to='hashtags.hashtag')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_hashtags', to='posts.post')),
            ],
            options={
                'db_table': 'post_hashtags',
                'indexes': [models.Index(fields=['hashtag', 'created_at'], name='idx_hashtag_created')],
                'constraints': [models.UniqueConstraint(fields=('post', 'hashtag'), name='uniq_post_hashtag')],
            },
        ),
    ]
