[tool.black]
line-length = 180
target-version = ["py312"]
exclude = '''
/(
  \.git
 | \.venv
 | build
 | dist
 | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 180
known_first_party = ["veilgram"]
combine_as_imports = true
