# Generated by Django 5.2.4 on 2025-08-09 03:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=128)),
                ('secret_hash', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_credentials',
                'indexes': [models.Index(fields=['user', 'device_id'], name='device_cred_user_id_71785b_idx'), models.Index(fields=['is_active'], name='device_cred_is_acti_b9ff9a_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
