# Generated by Django 5.2.4 on 2025-08-30 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('comments', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='comments.comment'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['comment'], name='idx_asset_comment'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('post__isnull', False), ('comment__isnull', False), _negated=True), name='asset_not_both_post_and_comment'),
        ),
    ]
