# Generated by Django 5.2.4 on 2025-09-11 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create_post', 'Create Post'), ('update_post', 'Update Post'), ('delete_post', 'Delete Post'), ('create_comment', 'Create Comment'), ('update_comment', 'Update Comment'), ('delete_comment', 'Delete Comment'), ('follow', 'Follow'), ('unfollow', 'Unfollow'), ('vote_poll', 'Vote Poll'), ('report_user', 'Report User'), ('report_post', 'Report Post'), ('report_comment', 'Report Comment')], db_index=True, max_length=32)),
                ('target_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('target_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('ua_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_user_created_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_created_idx'), models.Index(fields=['target_type', 'target_id', '-created_at'], name='audit_target_created_idx')],
            },
        ),
    ]
