# Generated by Django 5.2.4 on 2025-08-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
