# Generated by Django 5.2.4 on 2025-09-09 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.UUIDField()),
                ('verdict', models.CharField(max_length=16)),
                ('labels', models.JSONField(default=list)),
                ('score', models.FloatField(default=0.0)),
                ('matched', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'moderation_reports',
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='moderation__target__bb418a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('deny_keyword', 'Deny keyword'), ('deny_regex', 'Deny regex'), ('allow_keyword', 'Allow keyword')], max_length=32)),
                ('pattern', models.CharField(max_length=255)),
                ('lang', models.CharField(default='*', max_length=8)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'moderation_rules',
                'indexes': [models.Index(fields=['rule_type', 'lang', 'is_active'], name='moderation__rule_ty_c205b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('rule_type', 'pattern', 'lang'), name='uniq_rule_pattern_per_lang')],
            },
        ),
    ]
