# Generated by Django 5.2.4 on 2025-09-10 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_id', models.UUIDField(db_index=True)),
                ('author_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_entries',
                'indexes': [models.Index(fields=['user', '-created_at'], name='feed_entrie_user_id_b52e6c_idx')],
                'unique_together': {('user', 'post_id')},
            },
        ),
    ]
