from typing import Iterable, Dict, Any


class SearchBackend:
    # Index lifecycle
    def ensure_indices(self) -> None: ...
    def drop_indices(self) -> None: ...

    # Indexing
    def index_user(self, doc: Dict[str, Any]) -> None: ...
    def index_post(self, doc: Dict[str, Any]) -> None: ...
    def index_hashtag(self, doc: Dict[str, Any]) -> None: ...
    def bulk_index(self, kind: str, docs: Iterable[Dict[str, Any]]) -> None: ...

    # Searching
    def search_users(self, q: str, page: int, size: int) -> Dict[str, Any]: ...
    def search_posts(self, q: str, page: int, size: int) -> Dict[str, Any]: ...
    def search_hashtags(self, q: str, page: int, size: int) -> Dict[str, Any]: ...
